# -*- coding: utf-8 -*-

DEFAULT_PER_PAGE = 20

MIN_PASSWORD_LEN = 6
MAX_PASSWORD_LEN = 16

ADMIN_SESSION_KEY = 'admin'
ADMIN_TOKEN_TAG = 'admin'
ADMIN_LOGIN_VALID_DAYS = 7

WEIXIN_USER_COOKIE_KEY = 'weixin_user'
USER_TOKEN_TAG = 'user'
USER_LOGIN_VALID_DAYS = 90
